version: "3.8"
services:
  mongo:
    image: mongo:7
    container_name: weather-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: weatherdb
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "mongodb://localhost:27017/weatherdb",
          "--eval",
          "db.runCommand({ ping: 1 })",
        ]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
